"""streams

Revision ID: 0991e413dbb6
Revises: ae25c8faaeac
Create Date: 2020-04-02 09:56:42.447066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0991e413dbb6'
down_revision = 'ae25c8faaeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('streams', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'streams')
    # ### end Alembic commands ###
