"""added is_complete to mappa table

Revision ID: 19609f87f94f
Revises: 7bee08424dab
Create Date: 2020-04-14 16:50:59.549596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19609f87f94f'
down_revision = '7bee08424dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappa', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mappa', 'is_complete')
    # ### end Alembic commands ###
