"""added altitude_url to Activities

Revision ID: 5c3aef470fcd
Revises: 6355a15af154
Create Date: 2020-04-14 13:48:19.874248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3aef470fcd'
down_revision = '6355a15af154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('altitude_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'altitude_url')
    # ### end Alembic commands ###
