"""added maxs

Revision ID: 8d605f98b286
Revises: 0991e413dbb6
Create Date: 2020-04-05 15:40:35.469409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d605f98b286'
down_revision = '0991e413dbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('maxs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'maxs')
    # ### end Alembic commands ###
