"""changed datetime to string

Revision ID: a6074bae0995
Revises: 1bbfdce4962c
Create Date: 2020-02-02 15:18:22.449414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6074bae0995'
down_revision = '1bbfdce4962c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_timenow', table_name='activity')
    op.drop_index('ix_activity_timestamp', table_name='activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_activity_timestamp', 'activity', ['timestamp'], unique=False)
    op.create_index('ix_activity_timenow', 'activity', ['timenow'], unique=False)
    # ### end Alembic commands ###
