"""added start and end latlngs

Revision ID: ae25c8faaeac
Revises: e516643f2049
Create Date: 2020-03-01 09:30:45.873814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae25c8faaeac'
down_revision = 'e516643f2049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('end_lat', sa.String(length=64), nullable=True))
    op.add_column('activity', sa.Column('end_lng', sa.String(length=64), nullable=True))
    op.add_column('activity', sa.Column('start_lat', sa.String(length=64), nullable=True))
    op.add_column('activity', sa.Column('start_lng', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'start_lng')
    op.drop_column('activity', 'start_lat')
    op.drop_column('activity', 'end_lng')
    op.drop_column('activity', 'end_lat')
    # ### end Alembic commands ###
