"""empty message

Revision ID: be510dcc19cd
Revises: a6074bae0995
Create Date: 2020-02-02 17:55:46.621554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be510dcc19cd'
down_revision = 'a6074bae0995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('epoch', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'epoch')
    # ### end Alembic commands ###
