"""added commute

Revision ID: e516643f2049
Revises: 1aafbb0aaadd
Create Date: 2020-02-29 18:37:12.741638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e516643f2049'
down_revision = '1aafbb0aaadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('is_commute', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'is_commute')
    # ### end Alembic commands ###
